version: "3.9"
services:
  app:
    build: ./app
    depends_on:
      - redis-cache
      - user-service
    deploy:
      mode: replicated
      replicas: 2
    environment:
      JAVA_OPTS: "-Dspring.profiles.active=redis"
    ports:
      - "8080"


  user-service:
    build: ./user-service

  nginx:
    image: nginx:1.21.6
    volumes:
      - ./etc/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "8080:80"

  redis-cache:
    image: redis:6.2
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:v2.39.1
    ports:
      - "9090:9090"
    volumes:
      - ./etc/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:8.3.0
    ports:
      - "3000:3000"
    volumes:
      - ./etc/grafana/datasources:/etc/grafana/provisioning/datasources/
      - ./etc/grafana/dashboards-config:/etc/grafana/provisioning/dashboards/
      - ./etc/grafana/dashboards:/var/lib/grafana/dashboards
