management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

user-service:
  connectionTimeout: PT0.5S
  readTimeout: PT0.5S
  url: http://user-service:8080

spring:
  profiles:
    active: nocache
  redis:
    host: redis-cache
