{
 "title": "Cache caffeine",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Hit rps/Miss rps/Eviction rps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(cache_gets_total{result=\"hit\"}[1m])",
     "legendFormat": "Hit rps"
    },
    {
     "expr": "rate(cache_gets_total{result=\"miss\"}[1m])",
     "legendFormat": "Miss rps"
    },
    {
     "expr": "rate(cache_evictions_total[1m])",
     "legendFormat": "Evictions rps"
    },
    {
     "expr": "rate(cache_load_total{result=\"success\"}[1m])",
     "legendFormat": "Load rps"
    }
   ]
  },
  {
   "title": "Hit rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(cache_gets_total{result=\"hit\"}) / (sum(cache_gets_total{result=\"hit\"}) + sum(cache_gets_total{result=\"miss\"}))",
     "legendFormat": "Hit rate"
    }
   ]
  },
  {
   "title": "Cache size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "cache_size" }
   ]
  },
  {
   "title": "Average cache load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(delta(cache_load_duration_seconds[1m]))/sum(delta(cache_load_total{result=\"success\"}[1m]))",
     "legendFormat": "average cache load"
    }
   ]
  }
 ]
}