{
 "title": "Cart dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Endpoint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Special offer endpoint response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (quantile) (special_offer_seconds{exception=\"none\"})"
    }
   ]
  },
  {
   "title": "Special offer endpoint rps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (exception) (rate(special_offer_seconds_count[1m]))"
    }
   ]
  },
  { "title": "Caffeine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Hit rps/Miss rps/Eviction rps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(cache_gets_total{result=\"hit\"}[1m]))",
     "legendFormat": "Hit rps"
    },
    {
     "expr": "sum(rate(cache_gets_total{result=\"miss\"}[1m]))",
     "legendFormat": "Miss rps"
    },
    {
     "expr": "sum(rate(cache_evictions_total[1m]))",
     "legendFormat": "Evictions rps"
    },
    {
     "expr": "sum(rate(cache_load_total{result=\"success\"}[1m]))",
     "legendFormat": "Load rps"
    }
   ]
  },
  {
   "title": "Hit rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(cache_gets_total{result=\"hit\"}[1m])) / (sum(increase(cache_gets_total{result=\"hit\"}[1m])) + sum(increase(cache_gets_total{result=\"miss\"}[1m])))",
     "legendFormat": "Hit rate"
    }
   ]
  },
  {
   "title": "Cache size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    { "expr": "sum by (instance) (cache_size)" }
   ]
  },
  {
   "title": "Average cache load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(delta(cache_load_duration_seconds[1m]))/sum(delta(cache_load_total{result=\"success\"}[1m]))",
     "legendFormat": "average cache load"
    }
   ]
  },
  { "title": "Redis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Hit rps/Miss rps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(rate(redis_hit_count_total[1m]))",
     "legendFormat": "Hit rps"
    },
    {
     "expr": "sum(rate(redis_miss_count_total[1m]))",
     "legendFormat": "Miss rps"
    }
   ]
  },
  {
   "title": "Hit rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(redis_hit_count_total[1m])) / (sum(increase(redis_hit_count_total[1m])) + sum(increase(redis_miss_count_total[1m])))",
     "legendFormat": "Hit rate"
    }
   ]
  }
 ]
}